#!/usr/bin/env bash

for filename in $(ls -A dotfiles)
do
    DOTFILE="dotfiles/$filename"
    HOME_FILENAME="$HOME/$filename"

    if [ -f $HOME_FILENAME ]; then
        cp $HOME_FILENAME "$HOME_FILENAME.bak"
    fi

    cp $DOTFILE $HOME_FILENAME
done

VUNDLE_DIR="$HOME/.vim/bundle"
if [ ! -d $VUNDLE_DIR ]; then
    echo "Vundle doesn't exist.  Cloning vundle..."
    git clone git@github.com:VundleVim/Vundle.vim.git $VUNDLE_DIR/Vundle.vim
fi

if [ ! -d "$HOME/.config/zsh-git-prompt" ]; then
    git clone git@github.com:olivierverdier/zsh-git-prompt.git $HOME/.config/zsh-git-prompt
fi

